name: Run nix flake check

on:
  push:
  pull_request:

jobs:
  build:
    name: Flake Check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix flake check --log-format raw-with-logs -L

env:
  FORCE_COLOR: 1
